name: My First Worklfow

on: [push, fork]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        -   name: Welcome Message
            run: echo "My first Github Actions Job"
        
        -   name: Cloning the repo
            uses: actions/checkout@v4
        
        -   name: List the files (hidden also)
            run: ls -la
        
        -   name: Read file
            run: cat README.md